

import com.github.goive.steamapi.data.SteamApp;
import org.jsoup.Jsoup;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import com.github.goive.steamapi.data.SteamApp;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Michael
 */
public class GamePanel extends javax.swing.JPanel {
    /**
     * Creates SteamApp and MainBox
     */
    private MainBox mb;
    SteamApp game;
    
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
    }

    /**
     * Initializes GamePanel with the SteamApp provided 
     * @param app 
     */
    public GamePanel(SteamApp app)
    {
        initComponents();
        this.game = app;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        picturePanel = new javax.swing.JPanel();
        costLabel = new javax.swing.JLabel();
        gameNameLabel = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionBox = new javax.swing.JTextArea();
        addBtn = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(700, 125));

        picturePanel.setBackground(new java.awt.Color(153, 153, 153));
        picturePanel.setPreferredSize(new java.awt.Dimension(103, 103));

        javax.swing.GroupLayout picturePanelLayout = new javax.swing.GroupLayout(picturePanel);
        picturePanel.setLayout(picturePanelLayout);
        picturePanelLayout.setHorizontalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );
        picturePanelLayout.setVerticalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        costLabel.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        costLabel.setForeground(new java.awt.Color(255, 255, 255));
        costLabel.setText("Cost");

        gameNameLabel.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        gameNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        gameNameLabel.setText("Name");

        discountLabel.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        discountLabel.setForeground(new java.awt.Color(255, 255, 255));
        discountLabel.setText("Discount");

        descriptionBox.setEditable(false);
        descriptionBox.setBackground(new java.awt.Color(0, 0, 0));
        descriptionBox.setColumns(20);
        descriptionBox.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        descriptionBox.setForeground(new java.awt.Color(255, 255, 255));
        descriptionBox.setLineWrap(true);
        descriptionBox.setRows(1);
        descriptionBox.setToolTipText("");
        descriptionBox.setWrapStyleWord(true);
        descriptionBox.setAutoscrolls(false);
        descriptionBox.setMaximumSize(new java.awt.Dimension(571, 132));
        descriptionBox.setMinimumSize(new java.awt.Dimension(571, 132));
        jScrollPane1.setViewportView(descriptionBox);

        addBtn.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        addBtn.setText("Add");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(picturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(costLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 302, Short.MAX_VALUE))
                            .addComponent(gameNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(picturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * delegates to the MainBox to handle the adding of game
     * @param evt 
     */
    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked

    }//GEN-LAST:event_addBtnMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        mb.currentGameAddBtnClicked(game);
    }//GEN-LAST:event_addBtnActionPerformed

    /**
    * Sets the stored value game to the provided SteamApp and
    * sets the textFields accordingly to the new game
    * @param app 
    */
    public void setGame(SteamApp app)
    {
        game = app;
        setGameName(app.getName());
        setCost(app.getPrice());
        setDiscount("" + app.getPriceDiscountPercentage());
        setDescription(app.getAboutTheGame());
    }
    
    /**
     * returns the stored SteamApp
     * @return 
     */
    public SteamApp getGame()
    {
        return game;
    }
    
    /**
     * sets and stores a reference to the MainBox
     * @param mb 
     */
    public void setMainBox(MainBox mb)
    {
        this.mb = mb;
    }
    
    /**
     * sets the Title text field to the String
     * provided
     * @param name 
     */
    public void setGameName(String name)
    {
        gameNameLabel.setText(name);
    }
    
    /**
     * sets the Cost Text Field to the String
     * provided
     * @param cost 
     */
    public void setCost(String cost)
    {
        costLabel.setText("$" + cost);
    }
    
    /**
     * sets the Cost Text Field to the String
     * provided
     * @param cost 
     */
    public void setCost(double cost)
    {
        setCost(String.format("%.2f", cost));
    }
    
    /**
     * sets the Discount Text Field to the String
     * provided
     * @param disc 
     */
    public void setDiscount(String disc)
    {
        discountLabel.setText("%" + disc);
    }
    
    /**
     * sets the Description Text Area to the String 
     * provided
     * @param description 
     */
    public void setDescription(String description)
    {
    	
        descriptionBox.setText(Jsoup.parse(description).text());
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextArea descriptionBox;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JLabel gameNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel picturePanel;
    // End of variables declaration//GEN-END:variables
}
